# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/gen/*
    - lib/firebase_options.dart
  errors:
    invalid_annotation_target: ignore