targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/**/*_state.dart
            - lib/features/**/model/*.dart
            - lib/services/**/model/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/features/**/model/*.dart
            - lib/services/**/model/*.dart
        options:
          any_map: true
          explicit_to_json: true
          field_rename: snake
      # ref. https://twitter.com/_mono/status/1536907414490222593?s=20&t=RAVlvTxYiFwRkZZqETLR1A
      source_gen|combining_builder:
        options:
          ignore_for_file:
          - type=lint
          - implicit_dynamic_parameter
          - implicit_dynamic_type
          - implicit_dynamic_method
          - strict_raw_type
      theme_tailor:
        generate_for:
          include:
            - lib/theme/extensions/*.dart